version: '3.7'
services:
  django-jenkins:
    container_name: django-jenkins
    image: jairodh/django:v4
    restart: always
    environment:
       ALLOWED_HOSTS: "*"
       DB_DJANGO: django
       USER_DJANGO: django
       PWD_DJANGO: django
       HOST_DJANGO: mariadb-django-jenkins
       DJANGO_SUPERUSER_USERNAME: admin
       DJANGO_SUPERUSER_PASSWORD: admin
       DJANGO_SUPERUSER_EMAIL: admin@example.org
    ports:
       - 8085:8000
    depends_on:
       - db_django-jenkins
  db_django-jenkins:
    container_name: mariadb-django-jenkins
    image: mariadb
    restart: always
    environment:
       MARIADB_ROOT_PASSWORD: root
       MARIADB_DATABASE: django
       MARIADB_USER: django
       MARIADB_PASSWORD: django
    volumes:
       - vol-mariadb-django-jenkins:/var/lib/mysql
volumes:
    vol-mariadb-django-jenkins:
